name: Upload www to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - lets-XXX.fifthtry-community.com/**
      - .github/workflows/www-to-ft.yml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_XXX_WWW }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Upload to FifthTry using fastn
        run: cd lets-XXX.fifthtry-community.com/ && fastn upload lets-XXX-www
